version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: example
    container_name: vehicles-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - example

  db:
    image: mysql:8.0
    container_name: vehicles-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: Windowsaz@12
      MYSQL_PASSWORD: Windowsaz@12
      MYSQL_USER: laraveluser
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - example

  nginx:
    image: nginx:1.23.1-alpine
    container_name: vehicles-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - example

networks:
  example:
    driver: bridge

volumes:
  dbdata:
    driver: local